# Generated by Django 4.2.25 on 2025-11-01 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('season', models.CharField(choices=[('kharif', 'Kharif (Monsoon)'), ('rabi', 'Rabi (Winter)'), ('zaid', 'Zaid (Summer)')], max_length=20)),
                ('duration_days', models.IntegerField(help_text='Average crop duration in days')),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='crops/')),
            ],
        ),
        migrations.CreateModel(
            name='LandParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_name', models.CharField(max_length=100)),
                ('area', models.DecimalField(decimal_places=2, help_text='Area in acres', max_digits=10)),
                ('soil_type', models.CharField(choices=[('alluvial', 'Alluvial'), ('black', 'Black'), ('red', 'Red'), ('laterite', 'Laterite'), ('desert', 'Desert'), ('mountain', 'Mountain')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('soil_ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('organic_carbon', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage', max_digits=5, null=True)),
                ('nitrogen_level', models.CharField(blank=True, help_text='Low/Medium/High', max_length=20)),
                ('phosphorus_level', models.CharField(blank=True, help_text='Low/Medium/High', max_length=20)),
                ('potassium_level', models.CharField(blank=True, help_text='Low/Medium/High', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_parcels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FertilizerPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('nitrogen_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('phosphorus_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('potassium_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('organic_manure_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('compost_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('zinc_kg', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('boron_kg', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('estimated_fertilizer_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_yield', models.DecimalField(decimal_places=2, help_text='Expected yield in quintals', max_digits=10)),
                ('estimated_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('application_schedule', models.TextField(help_text='Timeline for fertilizer application')),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizer.crop')),
                ('land_parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizer_plans', to='fertilizer.landparcel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
