# Generated by Django 4.2.25 on 2025-11-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='expected_yield',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Average yield in quintals/acre', max_digits=6),
        ),
        migrations.AddField(
            model_name='crop',
            name='irrigation_schedule',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='market_price',
            field=models.DecimalField(decimal_places=2, default=2000.0, help_text='Average market price (Rs/quintal)', max_digits=8),
        ),
        migrations.AddField(
            model_name='crop',
            name='max_temperature',
            field=models.DecimalField(decimal_places=1, default=35.0, help_text='Maximum temperature (°C)', max_digits=4),
        ),
        migrations.AddField(
            model_name='crop',
            name='min_temperature',
            field=models.DecimalField(decimal_places=1, default=15.0, help_text='Minimum temperature (°C)', max_digits=4),
        ),
        migrations.AddField(
            model_name='crop',
            name='nitrogen_requirement',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='kg/acre', max_digits=6),
        ),
        migrations.AddField(
            model_name='crop',
            name='pest_diseases',
            field=models.TextField(blank=True, help_text='Common pests and diseases'),
        ),
        migrations.AddField(
            model_name='crop',
            name='phosphorus_requirement',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='kg/acre', max_digits=6),
        ),
        migrations.AddField(
            model_name='crop',
            name='planting_method',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='potassium_requirement',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='kg/acre', max_digits=6),
        ),
        migrations.AddField(
            model_name='crop',
            name='rainfall_requirement',
            field=models.CharField(choices=[('low', 'Low (300-500mm)'), ('medium', 'Medium (500-700mm)'), ('high', 'High (>700mm)')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='crop',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='crop',
            name='soil_ph_max',
            field=models.DecimalField(decimal_places=1, default=7.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='crop',
            name='soil_ph_min',
            field=models.DecimalField(decimal_places=1, default=6.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='crop',
            name='storage_info',
            field=models.TextField(blank=True, help_text='Storage requirements and shelf life'),
        ),
        migrations.AddField(
            model_name='crop',
            name='suitable_soil_types',
            field=models.CharField(default='alluvial,black', help_text='Comma-separated list of suitable soil types', max_length=200),
        ),
        migrations.AddField(
            model_name='fertilizerplan',
            name='target_yield',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target yield per acre (quintals)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='irrigation_type',
            field=models.CharField(blank=True, choices=[('irrigated', 'Irrigated'), ('rainfed', 'Rainfed')], max_length=20),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='rainfall_mm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Annual rainfall (mm)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='soil_ec',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Soil electrical conductivity (dS/m)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='duration_days',
            field=models.IntegerField(default=120, help_text='Average crop duration in days'),
        ),
        migrations.AlterField(
            model_name='fertilizerplan',
            name='estimated_yield',
            field=models.DecimalField(decimal_places=2, help_text='Expected yield in quintals (parcel total)', max_digits=10),
        ),
    ]
