# Generated by Django 4.2.25 on 2025-11-01 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity in quintals', max_digits=10)),
                ('pickup_location', models.CharField(max_length=200)),
                ('pickup_village', models.CharField(max_length=100)),
                ('pickup_district', models.CharField(max_length=100)),
                ('destination_market', models.CharField(max_length=200)),
                ('destination_district', models.CharField(max_length=100)),
                ('preferred_date', models.DateField()),
                ('flexible_dates', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransportOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=100)),
                ('vehicle_capacity', models.DecimalField(decimal_places=2, help_text='Capacity in quintals', max_digits=10)),
                ('offered_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.TextField(blank=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transport_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='transport.transportrequest')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['offered_price'],
            },
        ),
    ]
