# Generated by Django 4.2.25 on 2025-11-01 11:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportoffer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transportrequest',
            options={},
        ),
        migrations.RemoveField(
            model_name='transportoffer',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='transportoffer',
            name='message',
        ),
        migrations.RemoveField(
            model_name='transportoffer',
            name='offered_price',
        ),
        migrations.RemoveField(
            model_name='transportoffer',
            name='transport_request',
        ),
        migrations.RemoveField(
            model_name='transportoffer',
            name='vehicle_capacity',
        ),
        migrations.AddField(
            model_name='transportoffer',
            name='available_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transportoffer',
            name='available_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportoffer',
            name='capacity',
            field=models.DecimalField(decimal_places=1, default=5.0, help_text='Capacity in tons', max_digits=5),
        ),
        migrations.AddField(
            model_name='transportoffer',
            name='current_district',
            field=models.CharField(default='New Delhi', max_length=100),
        ),
        migrations.AddField(
            model_name='transportoffer',
            name='current_location',
            field=models.CharField(default='New Delhi', max_length=200),
        ),
        migrations.AddField(
            model_name='transportoffer',
            name='driver_name',
            field=models.CharField(default='Driver Name', max_length=100),
        ),
        migrations.AddField(
            model_name='transportoffer',
            name='driver_phone',
            field=models.CharField(default='9999999999', max_length=15),
        ),
        migrations.AddField(
            model_name='transportoffer',
            name='insurance_valid_till',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transportoffer',
            name='minimum_charge',
            field=models.DecimalField(decimal_places=2, default=1000.0, help_text='Minimum charge in Rs.', max_digits=8),
        ),
        migrations.AddField(
            model_name='transportoffer',
            name='preferred_routes',
            field=models.TextField(blank=True, help_text='Comma-separated list of preferred districts'),
        ),
        migrations.AddField(
            model_name='transportoffer',
            name='rate_per_km',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='Rate per kilometer in Rs.', max_digits=6),
        ),
        migrations.AddField(
            model_name='transportoffer',
            name='refrigerated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transportoffer',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='transportoffer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transportoffer',
            name='vehicle_number',
            field=models.CharField(default='DL01XX0000', max_length=20),
        ),
        migrations.AlterField(
            model_name='transportoffer',
            name='vehicle_type',
            field=models.CharField(choices=[('mini_truck', 'Mini Truck (1-3 tons)'), ('small_truck', 'Small Truck (3-7 tons)'), ('medium_truck', 'Medium Truck (7-12 tons)'), ('large_truck', 'Large Truck (12+ tons)'), ('refrigerated', 'Refrigerated Truck')], max_length=20),
        ),
        migrations.CreateModel(
            name='TransportMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_distance', models.DecimalField(decimal_places=1, help_text='Distance in kilometers', max_digits=6)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='proposed', max_length=20)),
                ('farmer_rating', models.IntegerField(blank=True, null=True)),
                ('farmer_review', models.TextField(blank=True)),
                ('transporter_rating', models.IntegerField(blank=True, null=True)),
                ('transporter_review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transport_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='transport.transportoffer')),
                ('transport_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='transport.transportrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
